### ISSUE TITLE
No restriction to genetic programming

### ISSUE THREAD

**Issue by akatzmann** [cpetry/AntSim#15]
Hey Chris,

I just saw the latest changes did a major step to integrate genetical programming into the ant simulator. This is a great step as I know that the genetic programming was one of your major aims you wanted to target with this simulation. This shows up especially in the new hive structure, containing genetic sequences even when not needed by the hive at all (hiveController.js).
However, I would highly suggest not to limit the code to this use case, since the simulation itself has way more in it than only doing genetic programming. Genetic programming finds good solutions to some scenarios classical algorithms can hardly be programmed for. Nevertheless it is a rare topic in AI engineering for games or game scenarios, mainly due to the fact, that hardcoded, fuzzy or machine learning based AIs in most cases will find solutions which will _at least_ be same successful.

I therefore suggest - before major code parts get changed to fit the genetic scenario only - to create a seperate class (GeneticHive) inheritting from Hive instead of modifying the Hive class to match the genetic scenario. Maybe the Ant class (since created by the hive) should although be linked to the respective Hive base class (e.g. GeneticHive for GeneticAntControllerCustom.js) to keep things simple here.

Greetz
Alex

**Comment by cpetry** [comment]
Hi Alex,

what exactly do you want the hive and the ants to be able to do? Do other algorithms need more information or control over these classes?
The controller are meant as restrictions to the user and the game itself (no one likes ants that can teleport or live forever...)
Why would you like to inherit from Hive instead of HiveController?

**Comment by cpetry** [comment]
Ah I think now I got your point.
You would like to create an extra layer for all genetic topics. Am I right?
This would bloat up the class structure a bit but well alright. It could be beneficial to future non genetic simulations to not confuse the developer.

**Comment by akatzmann** [comment]
Actually I'm quite a friend of higher class hierarchies, in case they support modularity, overview and clean code. Keeping in mind "The magical number 7 (plus minus 2)" makes things easy here. However, this should give us some room (7 classes in level 1, 49 classes in level 2, 343 classes in level 3, ...) ;-)

Back to your HiveController-argument: D'accord. :+1:

**Comment by cpetry** [comment]
@akatzmann: Please check and close if you think I nailed it.

**Comment by akatzmann** [comment]
Looks good so far. I was just struggeling with the following line:

`// Create hive
this.hives.push(new HiveGenetic(this.canvas, hivePos, this.settings, this.collisionObjects)); // i = hiveNumber`
in ./js/simulation.js:51 (see [here](https://github.com/akatzmann/AntSim/blob/5eae118f0465a5fbfb9595fd0dd6a6b9755bb13d/js/simulation.js#L51))

since this still implies genetic hives to be the only choise for now. However, I think this can be modularized way later on.
