### ISSUE TITLE
Error in ant coloring

### ISSUE THREAD

**Issue by akatzmann** [cpetry/AntSim#5]
Once you start a simulation and after that restart it with the simulation button - as i usually do when changing seeds - the colors of the ants now get mocked up. However, this error did not exist until merge, possibly not even after. I guess, it has to do with the changed ant numbering (somewhere between commit 14 (196df...) and 15.3 (b927b...)).

**Comment by cpetry** [comment]
Perhaps a unit test would be nice for that

**Comment by cpetry** [comment]
I changed the coloring since then to the ids of the hives created inside it's collider.
I wanted to reduce extra variables of not needed.
Now all hives have to be created before creating the ants.
Seems I created a bug with this.
